- name: Build with Buildozer
        run: |
          # Allow running as root without prompting
          export BUILDOZER_ALLOW_ROOT=1
          # Run the build
          python3 -m buildozer android debug
